### PR TITLE
Remove Zebra

### PR DESCRIPTION
**Pull request by dleovl**
Zebra doesn't really fit in the RootHide Bootstrap unless properly patched for FULL rootless repository support. Installing RootHide Patcher through Zebra gives a bunch of errors, and I think it's just too much for people (a lot have asked how to fix it). It's just better to use the patched Sileo that gives conversion warnings.

This PR may be hacky though, it was done manually, I don't know how much it will mess up the `.pbxproj` since it wasn't edited through Xcode (still builds regardless).

Built, installed, and tested on real hardware. Zebra is now no longer a default application. Seems to work fine with icon cache too.

### CODE REVIEW

**Review by znexo — APPROVED** [review]
Agreed, Zebra doesn’t work entirely, and many have to stick to using Sileo. All that was done was the removal of the deb and the installation process of it.

**Review by boat1337 — APPROVED** [review]
zebra can suck on my left nut

**Review by nerd137 — CHANGES_REQUESTED** [review]
add cydia pls

**Comment by dleovl** [comment]
> Agreed, Zebra doesn’t work entirely, and many have to stick to using Sileo. All that was done was the removal of the deb and the installation process of it.

Yeah, though what I'm not sure on is if the `.pbxproj` file is now corrupted. Still builds and works fine though.

**Comment by dleovl** [comment]
A good alternative to viewing rootful repositories is Postbox from https://postbox.news/

**Comment by roothide** [comment]
In the public release version we should add an option for users to choose whether to install Zebra/Sileo

**Comment by haxi0** [comment]
yea btw i think this is the right decision to remove zebra, it kinda works but buggy. anyways sileo is better modified for roothide

**Comment by roothide** [comment]
> yea btw i think this is the right decision to remove zebra, it kinda works but buggy. anyways sileo is better modified for roothide

kirb won't be happy, maybe we can add an option to let the user decide to install sileo/Zebra?

**Comment by boat1337** [comment]
> > yea btw i think this is the right decision to remove zebra, it kinda works but buggy. anyways sileo is better modified for roothide
> 
> kirb won't be happy, maybe we can add an option to let the user decide to install sileo/Zebra?

Zebra being bundled would only be a good idea if it was properly patched for both rootless and roothide, which it isn't.

**Comment by dleovl** [comment]
> > > yea btw i think this is the right decision to remove zebra, it kinda works but buggy. anyways sileo is better modified for roothide
> > 
> > 
> > kirb won't be happy, maybe we can add an option to let the user decide to install sileo/Zebra?
> 
> Zebra being bundled would only be a good idea if it was properly patched for both rootless and roothide, which it isn't.

This is exactly it. I think it's a little too much effort than its worth, needs to properly support both rootless repositories and roothide patching. Currently, you can't even install roothide Patcher with it.

**Comment by wwg135** [comment]
agree to delete zebra！！

**Comment by dleovl** [comment]
Duplicate of #235

**Pull request closed without merging**
