### PR TITLE
zh_TW Translation

### PR DESCRIPTION
**Pull request by olivertzeng**

### CODE REVIEW

**Review by roothider — APPROVED** [review]

**Comment by roothider** [comment]
can you fix conflicts?

**Comment by olivertzeng** [comment]
> can you fix conflicts?

Ok

**Comment by olivertzeng** [comment]
@roothider ive fixed that

**Comment by olivertzeng** [comment]
no offense but as a taiwanese im better at translating zh_TW than the original translator who seems to be a chinese

**Pull request merged**
