### PR TITLE
SwiftUI UI

### PR DESCRIPTION
**Pull request by haxi0**
New UI

### CODE REVIEW

**Comment by jrapf32** [comment]
the openssh toggle for the swift ui doesn’t work but it works on the normal ui

**Comment by haxi0** [comment]
i need help from roothidedev, which he doesnt give me

**Comment by haxi0** [comment]
well, i guess hes busy so thats ok :)

**Comment by dleovl** [comment]
common haxi0 w

**Comment by boat1337** [comment]
haxi0 is the goat

**Pull request merged**
