### PR TITLE
Remove Zebra

### PR DESCRIPTION
**Pull request by Mikasa-san**
Zebra is still breaking people dpkg so for now we should removes it and adds it later. Sorry Kirb

### CODE REVIEW

**Comment by dleovl** [comment]
More information about **why** available on the now closed PR #58

**Comment by roothider** [comment]
I'd like to keep zebra for @kirb, if it has any bugs on Bootstrap please provide details to reproduce and I'll fix it.
or if anyone would like to make a package manager selector UI for users to choose their preferred package manager when installing bootstrap, I'd be happy to merge the PR.

**Comment by dleovl** [comment]
> I'd like to keep zebra for @kirb, if it has any bugs on Bootstrap please provide details to reproduce and I'll fix it. or if anyone would like to make a package manager selector UI for users to choose their preferred package manager when installing bootstrap, I'd be happy to merge the PR.

The thing is, Zebra needs to be patched to warn about tweak conversion to roothide. It doesn't do that, at all.

It's not any hate against Zebra itself, or the developer, it's just that **more work** needs to be done for it. Try installing roothide Patcher in Zebra, you'll see what I mean.

Zebra is not functional. Not sure why this is closed, because **SOMETHING** has to be done with Zebra, as it's not enough in its current state.

**Comment by roothider** [comment]
> > I'd like to keep zebra for @kirb, if it has any bugs on Bootstrap please provide details to reproduce and I'll fix it. or if anyone would like to make a package manager selector UI for users to choose their preferred package manager when installing bootstrap, I'd be happy to merge the PR.
> 
> The thing is, Zebra needs to be patched to warn about tweak conversion to roothide. It doesn't do that, at all.
> 
> It's not any hate against Zebra itself, or the developer, it's just that **more work** needs to be done for it. Try installing roothide Patcher in Zebra, you'll see what I mean.
> 
> Zebra is not functional. Not sure why this is closed, because **SOMETHING** has to be done with Zebra, as it's not enough in its current state.

Zebra has not been heavily patched, it is mainly used to install tweaks that have been updated for rh, especially when sileo doesn't work for some reason, users always have a package manager available. when rootide dopamine was first released, sileo did not have those heavy patches like the current zebra. at that time, we released rh PostBox to convert tweaks in conjunction with the patcher. we added those patches for sileo because many users were not used to PostBox. If enough packages are updated for rh, then actually sileo won't need those heavy patches.

**Comment by roothider** [comment]
so it might be better to add an option to ask the user if they need to install Zebra when installing bootstrap i think

**Comment by dleovl** [comment]
> so it might be better to add an option to ask the user if they need to install Zebra when installing bootstrap i think

Right, but you can't even patch tweaks with it. I wouldn't give it an option to be installed / be provided by default if it doesn't work properly. It needs to be fixed to actually **work**. People will pick Zebra coming from previous jailbreak tools, and ask why it isn't installing tweaks properly.

Recreate the scenario by uninstalling roothide Patcher from Sileo and attempting to install it from Zebra.

**Comment by roothider** [comment]
> > so it might be better to add an option to ask the user if they need to install Zebra when installing bootstrap i think
> 
> Right, but you can't even patch tweaks with it. I wouldn't give it an option to be installed / be provided by default if it doesn't work properly. It needs to be fixed to actually **work**. People will pick Zebra coming from previous jailbreak tools, and ask why it isn't installing tweaks properly.
> 
> Recreate the scenario by uninstalling roothide Patcher from Sileo and attempting to install it from Zebra.
> 
> You'll notice
> 
> 1. You can't install roothide Patcher
> 2. Other tweaks you install will fail to install because of changed deb architecture (and no prompt to patch)

IMG_38FC362E8140-1

**Comment by roothider** [comment]
It seems that zebra is not handling dependencies correctly when installing certain procursus packages. this issue is not caused by roothide, it has the same issue on rootless. I should see if I can fix it once I have time.
IMG_0004

**Comment by dleovl** [comment]
> It seems that zebra is not handling dependencies correctly when installing certain procursus packages. this issue is not caused by roothide, it has the same issue on rootless. I should see if I can fix it once I have time. IMG_0004

That seems more like it. Yeah, this PR can be closed if that's fixed, because then it allows people to properly use Zebra.

Should've elaborated; roothide Patcher can be installed if you have the dependencies, but the actual dependencies themselves prevent it from being installed on a fresh bootstrap.

**Comment by roothider** [comment]
IMG_0EE8922DC784-1

**Comment by roothider** [comment]
the new version of sileo/zebra will be released together with Bootstrap 1.2

**Comment by dleovl** [comment]
> the new version of sileo/zebra will be released together with Bootstrap 1.2

Does this

**Comment by dleovl** [comment]
> Zebra is still breaking people dpkg

Can you elaborate on this?

**Pull request closed without merging**
